import { Injectable } from '@angular/core';
import {HttpClient, HttpHeaders} from "@angular/common/http";

@Injectable({
  providedIn: 'root'
})
export class ApiCallerService {
  header = new HttpHeaders({
    'Content-Type': 'application/json',
    'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJITlhWT3dMMVNwaXRINmh0Q052aVJPSjlrcjFSd05PM3NqckVqbTdlWUswIn0.eyJleHAiOjE2ODA2NDg0OTgsImlhdCI6MTY4MDYyNjg5OCwianRpIjoiYWFhNjljYmQtYmZiOC00YWU1LTllZTMtYTVhZWQ2NjYyOTgwIiwiaXNzIjoiaHR0cDovLzE4NS45OC4xMzYuNjA6ODA4MC9yZWFsbXMvY29kZWxlbWFucyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJiZjM4YjAxNi1jZTNkLTRjMDMtOTdiNC0yNTYxY2MzNDBiNTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcHAtZGVmaS0yNGgiLCJzZXNzaW9uX3N0YXRlIjoiMDMxN2I0ZGQtNDhhYi00NjJhLThhNzgtN2YyYjZjNzkyODk5IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtY29kZWxlbWFucyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjAzMTdiNGRkLTQ4YWItNDYyYS04YTc4LTdmMmI2Yzc5Mjg5OSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJsZXMtaW5mb3RlbGllbiIsInRlYW1faWQiOiIxNiIsImdpdmVuX25hbWUiOiIiLCJmYW1pbHlfbmFtZSI6IiIsInRlYW1fbmFtZSI6IkxlcyBJbmZvdGVsaWVuIn0.fji7gdJNEzbouRCMoWaw_BrYL6DX1QZhNL5aEobmg2vljAJgoq9eA-HtvC2n5fuZ5UBzI10FsRO-epT7twRVd2yL7-jqMx6-01pulcJI0cxpBN81WSdQLn6KOWju2u5AUwpbLgWJhtU9Wd6vQ9bXN1OYtqbD199HAb9WYqBUDB663rXMzK09E6hD3T24WZKmsestfbFNILnS2HMiIcurz4kxfFbuhBJRLPp0I4qem7gRx7OL1TNjp3auDjljFHyZlEs1w2OGLsfcQ-gqoj-uqR_g2OmZeHOlyzHZsvVE_Pulbgp1o4pzYI8imHOJgqE3oFs5KNQORkT9DsafbxDNtQ'
  })
  constructor(private http_client: HttpClient) { }

  getHeader() : HttpHeaders {
    return this.header;
  }

}
